# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: '#about'
    weight: 10
  - name: 团队
    url: '#project'
    weight: 30
  - name: 出版物
    url: '#featured'
    weight: 40
  - name: 合作者
    url: '#accomplishments'
    weight: 50 
  - name: 博文
    url: '#posts'
    weight: 60
  - name: 联系我们
    url: '#contact'
    weight: 80
  - name: 加入我们
    url: '#demo_join_us'
    weight: 90
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
